.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 14.12.09             \" DATE
.Dt pdfrasterize 1       \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify
.Nm pdfrasterize
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line.
.Nd rasterize PDF documents
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op options
.Ar file                 \" file
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
converts a PDF document to bitmap files. Each PDF page is saved into a bitmap file. The bitmap file name is composed from the base name of the PDF file and the page number, prefixed with the adequate number of zeros so that all output file names are the same length.
.Sh OPTIONS
.Pp                      \" Inserts a space
The following options are available:
.Bl -tag -width -indent  \" Begins a tagged list
.It Fl h | -help
Print a summary of available commands and exit. No conversion is performed.
.It Fl o | -output-dir Ar dir
Sets the output directory to
.Ar dir
for converted bitmap files. It must point to an existing, writable directory. The default output directory is the current working directory.
.It Fl f | -format Ar fmt
Set bitmap file output format to
.Ar fmt .
The default format is png. Supported formats are:
.Pp
.Ar png
Portable Network Graphics
.Pp
.Ar jp2
JPEG 2000
.Pp
.Ar jpg
JPEG
.Pp
.Ar tiff
Tagged Image File Format
.Pp
.Ar gif
Graphics Interchange Format
.Pp
.Ar bmp
Windows bitmap
.Pp
.Ar psd
Adobe Photoshop document
.Pp
.Ar sgi
Silicon Graphics Image
.Pp
.Ar tga
Truevision TGA
.It Fl t | -transparent
Draw a transparent background instead of the default white background. This is only supported for
.Ar png ,
.Ar psd ,
.Ar sgi ,
.Ar tga
and
.Ar tiff
formats. No conversion will be performed if this option is used with another format.
.It Fl s | -scale Ar factor
Scale
.Ar factor
Default is 1.0. Use a factor >1.0 if you want higher quality rendering or <1.0 of you want thumbnails.
.It Fl p | -pages Ar ranges
Convert only specified pages. The
.Ar ranges
argument is a list of comma separated page ranges. E.g. 1,3-5,7 which is equivalent to 1,3,4,5,7 that would convert only pages 1, 3, 4, 5 and 7.
.El                      \" Ends the list
.Sh EXIT STATUS
.Nm
exits with 0 on success, and with >0 if an error occurs.
.Sh SEE ALSO
pdf2ppm(1)
.Sh AUTHOR
(c) 2009-2010 Cedric Luthi <cedric.luthi@gmail.com>
